### ISSUE TITLE
Bright/dark graining params

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deband#51]
In some situations, you may want to grain both the darker and brighter areas, but differently. Allowing the user to pass a `bright_grainer` and a `dark_grainer` might be a simple way to accomplish this, with `bright_grainer=None` being set to default. Alternatively, allowing stacking of multiple grainer (like Varde's graingasm function) might also be useful.

**Comment by Setsugennoao** [comment]
Should this be integrated in already existing function or a new one?
