### ISSUE TITLE
Add neo_f3kdb mode=5 support

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deband#53]
neo_f3kdb has recently added mode=5. This is current unsupported.

As this is a neo_f3kdb-only mode, an additional check must also be added to ensure regular f3kdb users can't trigger it without error. Furthermore, it seems neo has updated some things regarding the thresholds which may need additional looking at as well.

**Comment by wiwaz** [comment]
in addition to this, the new f3kdb build scales differently which vsdeband needs to account for,
