### ISSUE TITLE
sized_grain: Suggestions list

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-deband#55]
- [x] Remove AddGrain support since its redundant.
- [x] Grainfactory3 AVS has recently gotten significant updates, port over it's changes
- [x] Change default resample kernel to lanczos and allow it to be configurable.
- [x] Remove the reliance on resample kernel arguments to adjust sharpness, we could do a simple blur/sharpen convolution instead.
- [x] Add support for vs-noise type=4

**Comment by NSQY** [comment]
>     * [ ]  Add support for vs-noise type=4

Since type=4 (among others) is signal dependent; application on a blank clip is useless.

**Comment by Setsugennoao** [comment]
its*

**Comment by Setsugennoao** [comment]
Can i get a link to Grainfactory3 AVS?

**Comment by wiwaz** [comment]
https://github.com/Dogway/Avisynth-Scripts/blob/master/FilmGrain%2B.avsi

**Comment by Setsugennoao** [comment]
Moved the last missing thing in #92
