### ISSUE TITLE
Limitations/Missing functions

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-deband#8]
- Currently `f3kbilateral`, `f3kpf`, and `lfdeband` only support debanding using f3kdb.
- `f3kpf` has no configurable prefilter.
- There is currently no up to date and performant port of Gradfun3 to VS.
- Some legacy debandshit filters, such as the GuidedFilter-based debander are no longer included.

**Comment by NSQY** [comment]
f3kbilateral also breaks if you set ``radius`` too high, since the internal logic is not clamped.
