### ISSUE TITLE
Bug in sized_grain Expr expression?

### ISSUE THREAD

**Issue by adworacz** [Irrational-Encoding-Wizardry/vs-deband#85]
https://github.com/Irrational-Encoding-Wizardry/vs-deband/blob/ccdc6405d7144d4de651c9902618a68c3a7bee8c/vsdeband/noise.py#L118-L121

I was just reading the code, and it looks like this might be a bug? Perhaps a missing `else` statement to handle when Akarin isn't available?

**Comment by Setsugennoao** [comment]
Yeep, looks like it. I wonder what merge commit broke this :/
Thanks for cstching it. @LightArrowsEXE can you fix it?
