### ISSUE TITLE
Placebo: add static grain support

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deband#87]
My original PR had static grain support. It'd be nice to see this be implemented.

Alternatively, if that is not in the cards right away, it'd be nice `sized_grain`'s `dynamic` was set to `None` and it'd automatically default to `False` for grainers that support static grain, and `True` for grainers that don't. This follows current default behaviour whenever possible, without showing an error message every time someone uses for example `Placebo`.

**Comment by Setsugennoao** [comment]
I'm rewriting the entirety of grainer so this is useless as issue tracker.
Plus, i don't like it being unclear if you're going to have dynamic or static grain.
