### ISSUE TITLE
Implement new thresholds and drop f3kdb

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/vs-deband#9]
neo_f3kdb now properly handles thresholds, negating the need to merge multiple f3kdb calls:

https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb/commit/343632575349da929d1b862b948998367c011a43
https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb/discussions/16

In addition to the extra sample modes provided, usage of the original f3kdb plugin seems rather redundant. One thing to be considerate of is that threshold scaling is different; if implemented default values should be revised.

![tmp](https://user-images.githubusercontent.com/34185288/190194089-3e2cfd6f-ed98-4741-9923-2595e2e4ef36.png)

**Comment by Setsugennoao** [comment]
Fixed in #13
