### ISSUE TITLE
Implement fade edges

### ISSUE THREAD

**Issue by oZanderr** [Irrational-Encoding-Wizardry/vs-deband#90]
Currently, the grainers don't have an option to fade out grain around limited range values. As a consequence, they'll grain dark areas such as letterboxing, black frames, etc. This isn't ideal behavior and it looks especially bad on screens that can display it properly like OLEDs where you can cleary see the grain in these areas.

Comparison: https://slow.pics/c/x24jqriV

**Comment by Setsugennoao** [comment]
Added in https://github.com/Irrational-Encoding-Wizardry/vs-deband/commit/fbe153896380c9b0e9580e15970f3acf9ba4e7e6
