### ISSUE TITLE
Placebo grain issues

### ISSUE THREAD

**Issue by wiwaz** [Irrational-Encoding-Wizardry/vs-deband#91]
Graining at 32bit float significantly brightens the image
Chroma grain only adds pink grains, using the plugin directly does not have this issue.

**Comment by Setsugennoao** [comment]
Minimum example code?
Is it Placebo.deband with grain or PlaceboGrain

**Comment by wiwaz** [comment]
The latter, though its possible the former is also affected
Can be reproduced just by graining with chroma enabled

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-deband/commit/c2d314b8c8237ca6b5bde8d5cc36d820e1fc64bf
